/**
 * Sprite drawing with a two-tier art system:
 *   1. If a custom image exists at /assets/items/<id>.png (generated by
 *      the Gemini pipeline in scripts/), we use it.
 *   2. Otherwise we fall back to crisp emoji rendering.
 *
 * Characters can have a second animation frame at /assets/items/<id>_2.png;
 * animatedId() flips between the two frames like classic 2-frame cartoon
 * animation when the second frame exists.
 */

const images = new Map<string, HTMLImageElement>();

/** Kick off a background load for a custom sprite; harmless if it 404s. */
export function preloadSprite(id: string): void {
  if (images.has(id)) return;
  const img = new Image();
  img.src = `/assets/items/${id}.png`;
  img.onload = () => images.set(id, img);
  img.onerror = () => {
    /* no custom art — emoji fallback will be used */
  };
}

/** Flip between <id> and <id>_2 at the given rate, if frame 2 exists. */
export function animatedId(id: string, time: number, fps = 5): string {
  if (!images.has(`${id}_2`)) return id;
  return Math.floor(time * fps) % 2 === 0 ? id : `${id}_2`;
}

export function drawSprite(
  ctx: CanvasRenderingContext2D,
  id: string,
  emoji: string,
  x: number,
  y: number,
  size: number,
  rotation = 0,
  flipX = false,
  anchor: 'center' | 'bottom' = 'center',
): void {
  ctx.save();
  // Whole-pixel positions keep color-emoji glyphs rasterizing stably from
  // frame to frame; fractional positions make them shimmer on some devices.
  ctx.translate(Math.round(x), Math.round(y));
  if (rotation !== 0) ctx.rotate(rotation);
  if (flipX) ctx.scale(-1, 1);

  const img = images.get(id);
  if (img) {
    // Fit within size while preserving the sprite's aspect ratio.
    const ratio = img.width / img.height;
    const w = ratio >= 1 ? size : size * ratio;
    const h = ratio >= 1 ? size / ratio : size;
    ctx.drawImage(img, -w / 2, anchor === 'bottom' ? -h : -h / 2, w, h);
  } else {
    ctx.font = `${size}px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(emoji, 0, anchor === 'bottom' ? -size * 0.42 : size * 0.06);
  }
  ctx.restore();
}
